name: Casters
version: 1.1
author: SirGoldenNugget
main: Cast.Main
description: Casters Plugin.
commands:
    casters:
        description: Lists All Casters Commands.
    cast:
        description: Lists All Cast Commands.
    wand:
        description: Lists All Wand Commands.
    chat:
        description: Lists All Chat Commands.
    party:
        description: Lists All Party Commands.