name: Casters
version: 1.1
author: SirGoldenNugget
main: Cast.Main
description: CasterCommands Plugin.
commands:
    casters:
        description: Lists All CasterCommands Commands.
    cast:
        description: Lists All Cast Commands.
    casts:
        description: List All Casts In Inventory.
    wand:
        description: Lists All Wand Commands.
    chat:
        description: Lists All Chat Commands.
    party:
        description: Lists All Party Commands.